### ISSUE TITLE
woondossier/docusaurus-terminology

### ISSUE THREAD

**Issue by codedust** [LunaticMuch/docusaurus-terminology#3]
How is this repo different from https://github.com/woondossier/docusaurus-terminology?

**Comment by LunaticMuch** [comment]
It's a single package, instead of two. Updated dependencies where possible, although some lile `globby` are ESM only now and docusaurus does not yet support ESM for plugins as per https://github.com/facebook/docusaurus/issues/6520
Published and actively maintained on NPM. 

I am realizing I forgot to publish the roadmap of additional changes, which are
- add support for tooltip options
- add option to chose between tooltip and popover
- support for custom tooltip component
